# .gitlab-ci.yml

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:16-alpine
  before_script:
    - npm install
  script:
    - npm test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker login -u achei -p Nalian@2020
  script:
    - docker build -t achei/react-continous-intergration:latest .
    - docker push achei/react-continous-intergration:latest

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker pull achei/react-continous-intergration:latest
